title: "jkmgeo"
author: "James K. Muller"
description: "James Muller's website"

# 
# SOCIAL NETWORKS
# 
# production_url : https://jkmgeo.github.io
email: "jkmgeo@protonmail.com"
github_username: "jkmgeo"
twitter_username: "jmullergeo"

# 
# STYLING
# 
theme: "minima"

plugins:
  - jekyll-sitemap

# 