title: jkmgeo
author: James K. Muller
email: jkmgeo@protonmail.com
description: (c) 2022

github_username: jkmgeo
twitter_username: jmullergeo

header_pages:
- til/index.md

theme: minima

plugins:
  - jekyll-sitemap
