title: jkmgeo
author: James K. Muller
email: jkmgeo@protonmail.com
description: website for James K. Muller, geoscientist

github_username: jkmgeo
twitter_username: jmullergeo

header_pages:
- index.md
- ./til/index.md

theme: minima

plugins:
  - jekyll-sitemap
