title: jkmgeo
author: 
  name: James K. Muller
  email: jkmgeo@protonmail.com
description: website for James K. Muller, geoscientist

social_links:
  github: jkmgeo
  twitter: jmullergeo

header_pages:
- index.md
- ./til/index.md
theme: "minima"

plugins:
  - jekyll-sitemap
